Driver modification
jrgnicho/dynamixel-workbench pull request #1
Opened 2017-06-22 20:11 UTC by marip8

This PR adds a parameter call `joint` (default ="") with which the user can specify which joint of the URDF to drive with the joint state message output of the Dynamixel. That joint name is then written to the first entry of the joint state message `name` field in the `InitRos` method.

Without it, the joint state and robot state publishers do not know which frames to move with the input joint value from the Dynamixel

2017-06-24 18:40 UTC, jrgnicho requested changes

2017-06-24 18:40 UTC, jrgnicho commented on dynamixel_workbench_single_manager/src/dynamixel_driver.cpp
> +  if(!joint_.empty())
This should throw an error if no name is provided.

2017-06-24 18:40 UTC, jrgnicho commented on dynamixel_workbench_single_manager/src/dynamixel_driver.cpp
> +  ph.param("joint", joint, std::string(""));
The default should be a non-empty string

2017-06-24 18:40 UTC, jrgnicho commented on dynamixel_workbench_single_manager/src/dynamixel_driver.cpp
> +    joint_(joint)
I'd be more confortable with `joint_name_` instead of `joint_`

2017-06-26 14:36 UTC, marip8 commented on dynamixel_workbench_single_manager/src/dynamixel_driver.cpp
> +  if(!joint_.empty())
Having a joint name in the name field of the joint state message isn't critical for the driver to operate, so should we really throw an error? Maybe there would be a situation where you want to actuate the motor, but don't really care about it being tied to a URDF frame

2017-06-26 14:39 UTC, marip8 commented on dynamixel_workbench_single_manager/src/dynamixel_driver.cpp
> +  ph.param("joint", joint, std::string(""));
If we want to leave the option of using the driver without specifying a joint name, I would rather leave the string empty than give it a default name that might end up being a name of a URDF joint

2017-06-26 22:18 UTC, jrgnicho requested changes

2017-06-26 22:18 UTC, jrgnicho commented on dynamixel_workbench_single_manager/src/dynamixel_driver.cpp
> +  if(!joint_.empty())
At the very least a warning should be thrown.

2017-06-26 22:18 UTC, jrgnicho commented on dynamixel_workbench_single_manager/src/dynamixel_driver.cpp
> +  ph.param("joint", joint, std::string(""));
I think having an empty string could make it harder to find bugs related to forgetting to set the joint ros parameter, plus there's no harm  in having a default name such as "dynamixel_joint" or something along those lines.

2017-06-26 22:18 UTC, jrgnicho commented on dynamixel_workbench_single_manager/include/dynamixel_workbench_single_manager/dynamixel_driver.h
> + std::string joint_;
Could this be renamed to `joint_name_`?

2017-06-30 14:28 UTC, jrgnicho approved these changes

2017-06-30 14:28 UTC, merged

2017-06-30 14:28 UTC, jrgnicho commented
@marip8  thanks for the contribution.